server:
  port: 8888


spring:
  application:
    name: config-service
  profiles:
    active: native

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: file:///c:/dev/inflearn-msa-practice/
          uri: https://github.com/lcg0826/inflearn-msa-practice.git
#          username:
#          password:
        native:
          # search-locations: file:///${user.home}/dev/native-file-repo
          search-locations: file:///C:/dev/native-file-repo
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
