server:
  port: 8888


spring:
  application:
    name: config-service
  profile:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/dev/native-file-repo
        git:
#          uri: file:///c:/dev/inflearn-msa-practice/
          uri: https://github.com/lcg0826/inflearn-msa-practice.git
#          username:
#          password:


