server:
  port: 8888


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///c:/dev/inflearn-msa-practice/
          uri: https://github.com/lcg0826/inflearn-msa-practice.git
#          username:
#          password:


